  FROM node:20
  WORKDIR /app/client
  COPY client/package*.json ./
  RUN npm install
  COPY client/ ./
  RUN npm run build
  RUN npm install -g serve
  CMD ["serve", "-s", "dist", "-l", "3000"]